---
experiment:
  name: graphembed/utzappos/base
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: must_cge
  dropout: true
  norm: true
  nlayers: 2
  #fc_emb: 768,1024,1200
  fc_emb: 2048,1024,1200
  gr_emb: d4096,d
  attr_objs_fc_emb: 2048,2048
  branch_emb_init: word2vec
  emb_dim: 300
  emb_init: null
  graph_init: utils/utzappos-graph.t7
  image_extractor: resnet18
  train_only: true
training:
  batch_size: 128
  eval_val_every: 1
  load: 
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.5
  max_epochs: 60
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: test
  topk: 1
  workers: 8
  freeze_features: false
extra:
  lambda_attr: 0
  lambda_obj: 0
  lambda_sub: 0
  graph: false
  hardk: null
  cutmix: false
  cutmix_prob: 1.0
  beta: 1.0
  tem: 5
  objs_weights: 1.1
  l2_weights: 1.0
  warming_epoch: -1
  lr_decrease: 45
